apiVersion: v1
kind: Service
metadata:
  name: istio-test
  labels:
    app.kubernetes.io/name: istio-test

   
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.global.service.port }}
      targetPort:  {{ .Values.global.service.port }}
      protocol: TCP
      name: http-api
    - port: {{.Values.global.service.actuatorPort}}
      targetPort: {{.Values.global.service.actuatorPort}}
      protocol: TCP
      name: http-actuator
      
  selector:
      app.kubernetes.io/name: istio-test