FROM openjdk:11.0-jre
VOLUME /tmp
ENV JAVA_OPTS=""
ARG DEPENDENCY=build/libs
ARG MAINCLASS_ARG
ENV MAINCLASS=$MAINCLASS_ARG
COPY ${DEPENDENCY}/BOOT-INF/lib /app/lib
COPY ${DEPENDENCY}/META-INF /app/META-INF
COPY ${DEPENDENCY}/BOOT-INF/classes /app
USER 1001
ENTRYPOINT ["sh","-c","java $JAVA_OPTS -cp app:app/lib/* $MAINCLASS"]