eureka:
  instance:
    preferIpAddress: true

  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://service-registry:8761/eureka
    healthcheck:
      enabled: true

spring:
  application:
    name: istio-debug
  main:
    cloud-platform: none

management.server.port: 8081